### ISSUE TITLE
mobile experience

### ISSUE THREAD

**Issue by ltalirz** [ltalirz/atomistic-software#57]
issues with the mobile experience

 - [x] legends take most of the space in the plots
        
![image](https://user-images.githubusercontent.com/1053245/127124551-3df0c0ac-215d-4760-9a26-58d81b37cc24.png)

 - [x] three boxes in statistics view are not floating and remain side-by-side
 - [ ] hover for abbreviations does not work in touch displays

**Comment by kjappelbaum** [comment]
i would maybe also collapse the navigation which takes a lot of space

**Comment by ltalirz** [comment]
> collapse the navigation which takes a lot of space

done in 207a9c9a2293e1064b4c97d97b11d8f81cbae115

**Comment by ltalirz** [comment]
legend position fixed in a5d474c9c16f406e4bdf314a0855d9123cdd88da

**Comment by ltalirz** [comment]
In the brave browser on my iphone, hover on abbreviations works when holding down on the abbreviation.

Unfortunately, the text gets selected at the same time... well, I'm not going to fix everything for the moment.
