### ISSUE TITLE
hoover is a bit sticky 

### ISSUE THREAD

**Issue by kjappelbaum** [ltalirz/atomistic-software#63]
using Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (x86_64)

![chrome-capture](https://user-images.githubusercontent.com/32935233/117539102-5ad47780-b009-11eb-8c6a-1e2742360893.gif)

**Comment by ltalirz** [comment]
Can you still reproduce this?  http://atomistic.software/#/charts/RASPA

I also vaguely remember seeing this some time before but now I cannot reproduce it myself

**Comment by ltalirz** [comment]
Closing this; feel free to reopen if issue resurfaces
