### ISSUE TITLE
print does not work

### ISSUE THREAD

**Issue by kjappelbaum** [ltalirz/atomistic-software#66]
using Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (x86_64)

perhaps simply remove this option? 

<img width="1437" alt="Screen Shot 2021-05-08 at 14 35 55" src="https://user-images.githubusercontent.com/32935233/117539404-c2d78d80-b00a-11eb-8b67-c81e62cc1911.png">

**Comment by kjappelbaum** [comment]
revise: it just takes forever to load ...

**Comment by ltalirz** [comment]
I just removed the print button - I can't see a point in having it
