### ISSUE TITLE
html in notes not rendered 

### ISSUE THREAD

**Issue by kjappelbaum** [ltalirz/atomistic-software#67]
<img width="1222" alt="Screen Shot 2021-05-08 at 14 37 45" src="https://user-images.githubusercontent.com/32935233/117539444-f7e3e000-b00a-11eb-81a1-9d2e56cc5995.png">

**Comment by ltalirz** [comment]
thanks, you seem to have caught the only case of HTML use in the `code.json`  file.
the easiest was just to remove this one in 7f7e7aebec882d51a001783c5d1589b266f9ee74
