### ISSUE TITLE
"Free" / "commercial" terminology

### ISSUE THREAD

**Issue by ltalirz** [ltalirz/atomistic-software#75]
@eimrek notes

> I don't like the opposition of "commercial" and "free", as commercial software can still be free (check e.g. intro of https://en.wikipedia.org/wiki/Commercial_software). [...] Molcas is based on the same open-source code of openmolcas, but on a stable version and they also give support. This is also, in a sense, a way to have a "commercial free open-source software", i.e. you just pay for the support.

**Comment by ltalirz** [comment]
You are right - I use "commercial" in the narrower sense of "pay to use", while it can certainly apply to "pay to x"  more generally. Is there a (widely known) alternative word that specifically means "pay to use"? 

I guess I could use "non-free" but in your example of a commercial open-source software, calling it "non-free open-source" software could be confusing since the term "free software" often refers to more than just the price of software.
There is also "proprietary" but this can be understood to mean "closed-source", which is not necessarily the case for "pay to use" software (e.g. Gaussian, VASP).

If you can come up with a better alternative, I'd be happy to adopt it - if not, I will probably stick with "commercial" and will simply clarify the definition in the manuscript.
In general, if you are aware of an authoritative source for the terminology around software licenses & business models, I'd be happy to adopt it.

**Comment by eimrek** [comment]
One alternative could be "paid software" but I agree that "commercial software" is acceptable, especially if there is clarification on what is meant.

**Comment by ltalirz** [comment]
Thanks for the suggestion. As a tendency, I agree that "paid software" is more specific than "commercial software", although "paid software" is still not very explicit on what the user is paying for (perhaps some would consider Red Hat Enterprise Linux paid software...).

Given that "paid software" seems to be significantly less common (1M hits for "paid software" vs 7.5M hits for "commercial software), I think I'll stick with "commercial software" for the time being and close this until new information / further feedback.

The main reason why I agree that this slight inaccuracy is acceptable is that atomistic-software focuses on usage patterns in academia, and academic users in computational materials science (in my experience) are unlikely to pay for support around a simulation software if they can have the software for free.
